### ISSUE TITLE
Voronoi Polygons

### ISSUE THREAD

**Issue by paul-vdb** [tmcd82070/SDraw#27]
Hello, 
I've been using the Voronoi polygons function (SDraw::voronoi.polygons) in your code for some spatial balance calculations and have had a real minor issue. You have the option to put in a bounding.polygon to clip the voronoi to this object. However, sometimes the rectangle that the voronoi is calculated under is a subset of the bounding box. When this occurs you can't actually add that extra space back later. As a result, some of my spatial points for my spatial balance calculations were not subset by the voronoi polygons. I've fixed this locally by not using the !missing(bounding.polygon) but instead adding the internal rectangle bounding box initially in the calculation of the voronoi from the outset.
z = deldir::deldir(crds[, 1], crds[, 2], rw = bbox)
This works well if you change bounding.polygon to accept a bounding box matrix and has solved my problems. 
Cheers,
Paul

**Comment by tmcd82070** [comment]
Paul,

Thank you very much.  We are working on an update to SDraw.  I will make
sure to get this change in.

*Trent McDonald*
* Senior Statistician*

Western EcoSystems Technology, Inc.
Environmental & Statistical Consultants
1610 Reynolds Street
Laramie, WY 82072
307-721-3172
307-755-9717
tmcdonald@west-inc.com
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by tmcd82070** [comment]
@paul-vdb : I've implemented this change, and pushed an update (re-install with devtools::install_github). 

Can you place in the comments of this issue ("Attach files by dragging & dropping" at the bottom of comment box) the point data and polygon to clip to that was giving you problems?  I was not able to replicate your error, and this will allow me to test.

**Comment by paul-vdb** [comment]
Thanks for the quick reply Trent. Below is an example that should show it with the the version I'm working with (Version 2.1.3). Should have mentioned that before. I'll download a new version soon.

set.seed(101)
pts <- SpatialPoints(cbind(runif(1000), runif(1000)))
smp <- pts[sample(1:length(pts), 10),]
bounding.poly <- as(extent(c(0,1,0,1)), 'SpatialPolygons')
vor <- SDraw::voronoi.polygons(smp, bounding.poly)
plot(vor)
points(pts, pch = 20)
points(smp, col = "red", pch = 20)
plot(bounding.poly, add = T,  border= "blue")

**Comment by tmcd82070** [comment]
@paul-vdb Thank you for the example.  I've left the !missing(bounding.poly) in case the bounding polygon is not a square.  Otherwise, I see now that it is essential to pass the bounding polygon's bbox to deldir.  If you don't, deldir adds 10% extent on it's own. 

I added the following example 
#'# Example clipping to fixed polygon (from @paul-vdb)
#'set.seed(101)
#'pts <- SpatialPoints(cbind(runif(1000), runif(1000)))
#'smp <- pts[sample(1:length(pts), 10),]
#'bound.pts <- cbind(c(0.2503111693,  0.5215198166,  0.8074680642,
#'                     0.9312807075,  0.9047494268,  0.7750409433,
#'                     0.3033737308,  0.0000000000,  0.0321650835,
#'                     0.0321650835),
#'                   c(0.03098592, 0.14595480, 0.03688176,
#'                     0.25502784, 0.89472650, 1.00000000,
#'                     0.80334098, 0.52918441, 0.14005896,
#'                     0.14005896))
#'bounding.poly <- SpatialPolygons(list(Polygons(list(Polygon(bound.pts)), "b")), as.integer(1))
#'vor <- SDraw::voronoi.polygons(smp, bounding.poly)
#'plot(vor)
#'points(pts, pch = 20)
#'points(smp, col = "red", pch = 20, cex=2)
#'plot(bounding.poly, border="green", lwd=2, add=T)

**Comment by paul-vdb** [comment]
Fantastic. I actually was rerunning this code two days ago by chance and was still doing ad-hoc fixes. I'll pull your new version down and use it. Thanks!
