### ISSUE TITLE
Error with lazy loading

### ISSUE THREAD

**Issue by dwalke44** [tmcd82070/SDraw#5]
I am trying to install SDraw using the devtools function 

>install_github("tmcd82070/SDraw").

When I use that command, I get the following error message:

"
* installing *source* package 'SDraw' ...
** R
** data
** inst
** preparing package for lazy loading
Error in writeOGR(UT_ecoregions, desktop, "UT_ecoregions", driver = "ESRI Shapefile",  : 
  Creation of output file failed
Error : unable to load R code in package 'SDraw'
ERROR: lazy loading failed for package 'SDraw'
* removing 'C:/Users/Dan Desktop/Documents/R/win-library/3.2/SDraw'
Error: Command failed (1)
"

I am using R version 3.2.1 on a 32-bit Windows 7.

**Comment by tmcd82070** [comment]
I've been out of the country.  Thank you for the comment.  Try again.

Jason (one of the programmers working on this) inadvertently placed a
vignette in the wrong directory, and this caused the error on lazy-load.
This has been fixed.

Trent

On Mon, Jun 22, 2015 at 1:20 PM, dwalke44 <notifications@github.com> wrote:

> I am trying to install SDraw using the devtools function
>
> install_github("tmcd82070/SDraw").
>
> When I use that command, I get the following error message:
>
> "
>
>    - installing *source* package 'SDraw' ... ** R ** data ** inst **
>    preparing package for lazy loading Error in writeOGR(UT_ecoregions,
>    desktop, "UT_ecoregions", driver = "ESRI Shapefile", : Creation of output
>    file failed Error : unable to load R code in package 'SDraw' ERROR: lazy
>    loading failed for package 'SDraw'
>    - removing 'C:/Users/Dan Desktop/Documents/R/win-library/3.2/SDraw'
>    Error: Command failed (1) "
>
> I am using R version 3.2.1 on a 32-bit Windows 7.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tmcd82070/SDraw/issues/5>.
>



-- 
 DWH ATTORNEY WORK PRODUCT / ATTORNEY-CLIENT COMMUNICATIONS


*Trent McDonald, PhD *
 *Senior Statistician*


Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-3172
(307) 760-4721 Cell
tmcdonald@west-inc.com
 www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by tmcd82070** [comment]
Issue closed.
